/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as TrainingCalendarRouteImport } from './routes/training-calendar'
import { Route as TrainingProgramsRouteImport } from './routes/training-programs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingCalendarRoute = TrainingCalendarRouteImport.update({
  id: '/training-calendar',
  path: '/training-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingProgramsRoute = TrainingProgramsRouteImport.update({
  id: '/training-programs',
  path: '/training-programs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/training-calendar': typeof TrainingCalendarRoute
  '/training-programs': typeof TrainingProgramsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/training-calendar': typeof TrainingCalendarRoute
  '/training-programs': typeof TrainingProgramsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/training-calendar': typeof TrainingCalendarRoute
  '/training-programs': typeof TrainingProgramsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/contact' | '/training-calendar' | '/training-programs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/contact' | '/training-calendar' | '/training-programs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/training-calendar'
    | '/training-programs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  TrainingCalendarRoute: typeof TrainingCalendarRoute
  TrainingProgramsRoute: typeof TrainingProgramsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training-calendar': {
      id: '/training-calendar'
      path: '/training-calendar'
      fullPath: '/training-calendar'
      preLoaderRoute: typeof TrainingCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training-programs': {
      id: '/training-programs'
      path: '/training-programs'
      fullPath: '/training-programs'
      preLoaderRoute: typeof TrainingProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  TrainingCalendarRoute: TrainingCalendarRoute,
  TrainingProgramsRoute: TrainingProgramsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
